// login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// signup
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// currentuser
export const CURRENT_USER_LOADING = 'CURRENT_USER_LOADING';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_FAILED = 'CURRENT_USER_FAILED';

// get All Students
export const GET_ALL_STUDENTS_LOADING = 'GET_ALL_STUDENTS_LOADING';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';
export const GET_ALL_STUDENTS_FAILED = 'GET_ALL_STUDENTS_FAILED';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REMOVE = 'REMOVE';
export const LOGIN_VALIDATION_EMAIL = 'LOGIN_VALIDATION_EMAIL';
export const LOGIN_VALIDATION_PASSWORD = 'LOGIN_VALIDATION_PASSWORD';
export const SIGNUP_VALIDATION_NAME = 'SIGNUP_VALIDATION_NAME';
export const SIGNUP_VALIDATION_EMAIL = 'SIGNUP_VALIDATION_EMAIL';
export const SIGNUP_VALIDATION_PASSWORD = 'SIGNUP_VALIDATION_PASSWORD';
export const SIGNUP_VALIDATION_TYPE = 'SIGNUP_VALIDATION_TYPE';
export const VALIDATION = 'VALIDATION';
export const REMOVE_ERROR_MESSAGES = 'REMOVE_ERROR_MESSAGES';
export const REMOVE_ERROR_MESSAGES_COMPANY = 'REMOVE_ERROR_MESSAGES_COMPANY';
export const ERROR_INFO_COMPANY = 'ERROR_INFO_COMPANY';
export const NEW_STUDENT = 'NEW_STUDENT';
export const PERVIOUS_DATA_OF_STUDENTS = 'PERVIOUS_DATA_OF_STUDENTS';
export const NEW_COMPANY = 'NEW_COMPANY';
export const PERVIOUS_DATA_OF_COMPANIES = 'PERVIOUS_DATA_OF_COMPANIES';
export const REMOVE_ERROR_MESSAGES_POST_COMPANY =
  'REMOVE_ERROR_MESSAGES_POST_COMPANY';
export const ERROR_POST_COMPANY = 'ERROR_POST_COMPANY';
export const NEW_VACANCIES = 'NEW_VACANCIES';
export const PERVIOUS_DATA_OF_VACANCIES = 'PERVIOUS_DATA_OF_VACANCIES';
export const BLOCK_COMPANY = 'BLOCK_COMPANY';
export const UN_BLOCK_COMPANY = 'UN_BLOCK_COMPANY';
export const BLOCK_STUDENT = 'BLOCK_STUDENT';
export const UN_BLOCK_STUDENT = 'UN_BLOCK_STUDENT';
export const BLOCK_LIST = 'BLOCK_LIST';
export const USER_IS_BLOCKED = 'USER_IS_BLOCKED';
export const USER_IS_NOT_BLOCKED = 'USER_IS_NOT_BLOCKED';
export const STUDENTS_UPDATION_REQUESTS = 'STUDENTS_UPDATION_REQUESTS';
export const COMPANIES_UPDATION_REQUESTS = 'COMPANIES_UPDATION_REQUESTS';
export const SAVE_STUDENT_UPDATION_DATA = 'SAVE_STUDENT_UPDATION_DATA';
export const SAVE_COMPANY_UPDATION_DATA = 'SAVE_COMPANY_UPDATION_DATA';
export const REQUEST_OF_STUDENT_ACCEPT = 'REQUEST_OF_STUDENT_ACCEPT';
export const REQUEST_OF_COMPANY_ACCEPT = 'REQUEST_OF_COMPANY_ACCEPT';
export const REQUEST_OF_STUDENT_REJECT = 'REQUEST_OF_STUDENT_REJECT';
export const REQUEST_OF_COMPANY_REJECT = 'REQUEST_OF_COMPANY_REJECT';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_VACANCY = 'DELETE_VACANCY';

export const APPLY_NOW_VACANCY_LOADING = 'APPLY_NOW_VACANCY_LOADING';
export const APPLY_NOW_VACANCY_SUCCESS = 'APPLY_NOW_VACANCY_SUCCESS';
export const APPLY_NOW_VACANCY_FAILED = 'APPLY_NOW_VACANCY_FALIED';

export const APPLY_VACANCY_DATA_LOADING = 'APPLY_VACANCY_DATA_LOADING';
export const APPLY_VACANCY_DATA_SUCCESS = 'APPLY_VACANCY_DATA_SUCCESS';
export const APPLY_VACANCY_DATA_FAILED = 'APPLY_VACANCY_DATA_FAILED';
