// login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// signup
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// currentuser
export const CURRENT_USER_LOADING = 'CURRENT_USER_LOADING';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_FAILED = 'CURRENT_USER_FAILED';

// get All Students
export const GET_ALL_STUDENTS_LOADING = 'GET_ALL_STUDENTS_LOADING';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';
export const GET_ALL_STUDENTS_FAILED = 'GET_ALL_STUDENTS_FAILED';

// delete companies access with admin
export const DELETE_COMPANY_LOADING = 'DELETE_COMPANY_LOADING';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_FAILED = 'DELETE_COMPANY_FAILED';

// delete student access with admin
export const DELETE_STUDENT_LOADING = 'DELETE_STUDENT_LOADING';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILED = 'DELETE_STUDENT_FAILED';

// logout
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// add new Student
export const NEW_STUDENT_LOADING = 'NEW_STUDENT_LOADING';
export const NEW_STUDENT_SUCCESS = 'NEW_STUDENT_SUCCESS';
export const NEW_STUDENT_FAILED = 'NEW_STUDENT_FAILED';

// add new Company
export const NEW_COMPANY_LOADING = 'NEW_COMPANY_LOADING';
export const NEW_COMPANY_SUCCESS = 'NEW_COMPANY_SUCCESS';
export const NEW_COMPANY_FAILED = 'NEW_COMPANY_FAILED';

// get All Companies
export const GET_ALL_COMPANIES_LOADING = 'GET_ALL_COMPANIES_LOADING';
export const GET_ALL_COMPANIES_SUCCESS = 'GET_ALL_COMPANIES_SUCCESS';
export const GET_ALL_COMPANIES_FAILED = 'GET_ALL_COMPANIES_FAILED';

// add new Vacancies
export const NEW_VACANCIES_LOADING = 'NEW_VACANCIES_LOADING';
export const NEW_VACANCIES_SUCCESS = 'NEW_VACANCIES_SUCCESS';
export const NEW_VACANCIES_FAILED = 'NEW_VACANCIES_FAILED';

// get all Vacancies
export const GET_ALL_VACANCIES_LOADING = 'GET_ALL_VACANCIES_LOADING';
export const GET_ALL_VACANCIES_SUCCESS = 'GET_ALL_VACANCIES_SUCCESS';
export const GET_ALL_VACANCIES_FAILED = 'GET_ALL_VACANCIES_FAILED';

// Apply Now Vacancy
export const APPLY_NOW_VACANCY_LOADING = 'APPLY_NOW_VACANCY_LOADING';
export const APPLY_NOW_VACANCY_SUCCESS = 'APPLY_NOW_VACANCY_SUCCESS';
export const APPLY_NOW_VACANCY_FAILED = 'APPLY_NOW_VACANCY_FALIED';

// Apply vacancy data
export const APPLY_VACANCY_DATA_LOADING = 'APPLY_VACANCY_DATA_LOADING';
export const APPLY_VACANCY_DATA_SUCCESS = 'APPLY_VACANCY_DATA_SUCCESS';
export const APPLY_VACANCY_DATA_FAILED = 'APPLY_VACANCY_DATA_FAILED';

// user is blocked
export const USER_IS_BLOCKED = 'USER_IS_BLOCKED';
